import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ModusProvider from "../components/ModusProvider";
import { ThemeProvider } from "../contexts/ThemeContext";
import AppHeader from "../components/AppHeader";
import AppFooter from "../components/AppFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Modus Next.js Web App",
  description: "Generated by create modus app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-background text-foreground`}
      >
        <ThemeProvider>
          <ModusProvider>
            <AppHeader />
            <div className="flex-1">{children}</div>
            <AppFooter />
          </ModusProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
