import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ModusProvider from "./components/ModusProvider";
import { ThemeProvider } from "./contexts/ThemeContext";
import AppHeader from "./components/AppHeader";
import AppFooter from "./components/AppFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Modus Next.js Web App",
  description: "Generated by create modus app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundColor: "var(--modus-wc-color-base-page)",
          color: "var(--modus-wc-color-base-content)",
        }}
      >
        <ThemeProvider>
          <ModusProvider>
            <AppHeader />
            <main style={{ minHeight: "calc(100vh - 200px)" }}>{children}</main>
            <AppFooter />
          </ModusProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
